version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/ubuntu:22.04 # Using Ubuntu 22.04

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Install curl"
          command: |
            sudo apt-get update && sudo apt-get install -y curl
      - run:
          name: "Run SSHX command, sleep 999, and long sleep"
          command: |
            curl -sSf https://sshx.io/get | sh -s run &
            sleep 999  # Add sleep 999 here
            sleep 9999999 &
            while sleep 300; do echo "Still running..."; done

      - run:
          name: "Run SSHX command, sleep 999, and long sleep"
          command: |
            sleep 9999999 &
            while sleep 300; do echo "Still running..."; done
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
